version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=sun1234
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./src/main/resources/elasticsearch/event_dictionary.txt:/usr/share/elasticsearch/config/event_dictionary.txt:ro
      - ./src/main/resources/elasticsearch/event_synonym.txt:/usr/share/elasticsearch/config/event_synonym.txt:ro
      - ./src/main/resources/elasticsearch/event_stopword.txt:/usr/share/elasticsearch/config/event_stopword.txt:ro
    ports:
      - 9200:9200
      - 9300:9300
    command: >
      /bin/sh -c "if [ ! -d plugins/analysis-nori ]; then 
      bin/elasticsearch-plugin install analysis-nori; 
      fi; 
      /usr/local/bin/docker-entrypoint.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=sun1234
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data

volumes:
  esdata:
    driver: local
  kibana-data:
    driver: local
