spring:
  profiles:
    active: local
  application:
    name: nugul-ticket
  data:
    redis:
      port: 6379
      host: localhost
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    
client:
  id: ${CLIENT_ID}

cloud:
  aws:
    s3:
      bucket: nugulticket
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

email:
  host: smtp.naver.com
  port: 465
  setForm: ${NAVER_EMAIL_USERNAME} # 발신자 이메일 주소
  password: ${NAVER_EMAIL_PASSWORD} #발신자 비밀번호

  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true # SSL 활성화